### ISSUE TITLE
Method GET in getter-setter usually is void

### ISSUE THREAD

**Issue by mazipan** [muhibbudins/lokasi#1]
In getter-setter pattern, get is return something but setter usually is void method.
Maybe you can follow this behavior. :-)
If user need to GET position after set, they need to call get again.

**Comment by muhibbudins** [comment]
Hmmm oke i like too, maybe i will remove their function. Cz tonight i feel maybe setter function must be return something. Thanks

**Comment by mazipan** [comment]
It's up to you to return something or not.
But follow the generic pattern will better I think.

**Comment by muhibbudins** [comment]
Haha oke its just another way to notify user if their action is succesful, cz sometimes user want to get something callback after the action execute ..
